// Generated by Dart Safe Data Class Generator. * Change this header on extension settings *
// ignore_for_file: type=lint
part of 'stylist_onboard_cubit.dart';

class StylistOnboardState extends BaseState {
  const StylistOnboardState._({
    required this.businessName,
    required this.address,
    required this.yearsOfExperience,
    required this.bio,
    required this.documentNumber,
    required this.imagePath,
    required this.updateBusinessInfoResult,
    required this.updateIdentityInfoResult,
    required this.photoPath,
    super.exception,
    super.isLoading,
  });

  const StylistOnboardState.initial()
      : this._(
          businessName: const StringInput.pure(),
          address: const StringInput.pure(),
          yearsOfExperience: const StringInput.pure(),
          bio: const StringInput.pure(),
          documentNumber: const StringInput.pure(),
          imagePath: const StringInput.pure(),
          photoPath: const StringInput.pure(),
          updateBusinessInfoResult: const ProcessState.init(false),
          updateIdentityInfoResult: const ProcessState.init(false),
        );

  final StringInput businessName;
  final StringInput address;
  final StringInput yearsOfExperience;
  final StringInput bio;
  final StringInput documentNumber;
  final StringInput photoPath;
  final StringInput imagePath;
  final ProcessState<bool> updateBusinessInfoResult;
  final ProcessState<bool> updateIdentityInfoResult;

  bool get canSubmitBusinessInfo =>
      Formz.validate([
        businessName,
        address,
        yearsOfExperience,
        bio,
      ]) &&
      !updateBusinessInfoResult.isLoading;

  bool get canSubmitIdentityInfo =>
      Formz.validate([
        documentNumber,
        imagePath,
        photoPath,
      ]) &&
      !updateIdentityInfoResult.isLoading;

  @override
  StylistOnboardState copyWith({
    StringInput? businessName,
    StringInput? address,
    StringInput? yearsOfExperience,
    StringInput? bio,
    StringInput? documentNumber,
    StringInput? imagePath,
    StringInput? photoPath,
    ProcessState<bool>? updateBusinessInfoResult,
    ProcessState<bool>? updateIdentityInfoResult,
    Exception? exception,
    bool? isLoading,
  }) {
    return StylistOnboardState._(
      businessName: businessName ?? this.businessName,
      address: address ?? this.address,
      yearsOfExperience: yearsOfExperience ?? this.yearsOfExperience,
      bio: bio ?? this.bio,
      documentNumber: documentNumber ?? this.documentNumber,
      imagePath: imagePath ?? this.imagePath,
      photoPath: photoPath ?? this.photoPath,
      updateBusinessInfoResult:
          updateBusinessInfoResult ?? this.updateBusinessInfoResult,
      updateIdentityInfoResult:
          updateIdentityInfoResult ?? this.updateIdentityInfoResult,
      exception: exception ?? this.exception,
      isLoading: isLoading ?? this.isLoading,
    );
  }

  @override
  List<Object?> get props => [
        businessName,
        address,
        yearsOfExperience,
        bio,
        documentNumber,
        imagePath,
        photoPath,
        updateBusinessInfoResult,
        updateIdentityInfoResult,
        exception,
        isLoading,
      ];
}
