// Generated by Dart Safe Data Class Generator. * Change this header on extension settings *
// ignore_for_file: type=lint
part of 'app_cubit.dart';

enum AuthStatus {
  unknown,
  unAuthenticated,
  authenticated,
}

class AppState extends Equatable {
  const AppState._({
    this.status = AuthStatus.unknown,
    this.user = const User(),
    this.platformSettings,
  });

  const AppState.initial([User? user, PlatformSettings? settings])
      : this._(
          status: AuthStatus.unknown,
          user: user ?? const User(),
          platformSettings: settings,
        );

  const AppState.unAuthenticated([PlatformSettings? settings])
      : this._(
          status: AuthStatus.unAuthenticated,
          user: const User(),
          platformSettings: settings,
        );

  const AppState.authenticated({required User user, PlatformSettings? settings})
      : this._(
          status: AuthStatus.authenticated,
          user: user,
          platformSettings: settings,
        );

  final AuthStatus status;
  final User user;
  final PlatformSettings? platformSettings;

  bool get isCustomer => user.role == 'customer';
  bool get isStylist => user.role == 'stylist';

  @override
  List<Object?> get props => [status, user, platformSettings];
}
