// Generated by Dart Safe Data Class Generator. * Change this header on extension settings *
// ignore_for_file: type=lint
import 'dart:io';

import 'package:auto_route/auto_route.dart';
import 'package:dotted_border/dotted_border.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:flutter_svg/svg.dart';
import 'package:iconsax/iconsax.dart';
import 'package:image_picker/image_picker.dart';
import 'package:path_provider/path_provider.dart';
import 'package:snip_fair/core/di/injector.dart';
import 'package:snip_fair/core/presentation/cubit/app_cubit.dart';
import 'package:snip_fair/core/presentation/theme/app_colors.dart';
import 'package:snip_fair/core/presentation/theme/app_textstyle.dart';
import 'package:snip_fair/core/presentation/widgets/app_text.dart';
import 'package:snip_fair/core/presentation/widgets/buttons/custom_button.dart';

import 'package:snip_fair/core/presentation/widgets/custom_appbar.dart';
import 'package:snip_fair/core/presentation/widgets/custom_text_field.dart';
import 'package:snip_fair/core/utils/app_helper.dart';
import 'package:snip_fair/core/utils/base/base_stateless_page.dart';
import 'package:snip_fair/core/utils/input/string_input.dart';
import 'package:snip_fair/features/stylists/onboard/cubit/stylist_onboard_cubit.dart';
import 'package:snip_fair/gen/assets.gen.dart';

@RoutePage()
class StylistBusinessIdVerifyScreen
    extends BaseStatelessPage<StylistOnboardCubit> implements AutoRouteWrapper {
  const StylistBusinessIdVerifyScreen({
    Key? key,
    this.fromSignUp = false,
  }) : super(key: key);

  final bool fromSignUp;

  @override
  Widget buildPage(BuildContext context) {
    final cubit = context.read<StylistOnboardCubit>();
    return BlocListener<StylistOnboardCubit, StylistOnboardState>(
      listenWhen: (previous, current) =>
          previous.updateIdentityInfoResult != current.updateIdentityInfoResult,
      listener: (context, state) {
        if (state.updateIdentityInfoResult.hasSuccess) {
          context.read<AppCubit>().onLogin();
        }
      },
      child: Scaffold(
        appBar: CustomAppBar(),
        body: SafeArea(
          child: SingleChildScrollView(
            child: Padding(
              padding: const EdgeInsets.all(24),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  40.verticalSpace,
                  SvgPicture.asset(Assets.images.logo),
                  12.verticalSpace,
                  const AppText(
                    text: 'Verify your identity',
                    color: Colors.black,
                    fontSize: 24,
                    fontWeight: FontWeight.bold,
                  ),
                  5.verticalSpace,
                  const AppText(
                    text: 'Upload a valid ID',
                  ),
                  20.verticalSpace,
                  DocumentPicker(
                    label: 'Government ID',
                    onSelected: cubit.onImagePathChanged,
                  ),
                  16.verticalSpace,
                  BlocSelector<StylistOnboardCubit, StylistOnboardState,
                      StringInput>(
                    selector: (state) {
                      return state.documentNumber;
                    },
                    builder: (context, documentNumber) {
                      return CustomTextField(
                        label: 'Document Number',
                        hint: 'Enter your bio',
                        isRequired: true,
                        onChanged: cubit.onDocNumberChanged,
                        isError: documentNumber.isNotValid,
                        descriptionText: documentNumber.displayError?.message,
                      );
                    },
                  ),
                  12.verticalSpace,
                  ImageTakerWidget(
                    label: 'Identification Proof(Take a photo holding your ID)',
                    onSelected: cubit.onPhotoPathChanged,
                  ),
                  12.verticalSpace,
                  16.verticalSpace,
                  BlocBuilder<StylistOnboardCubit, StylistOnboardState>(
                    builder: (context, state) {
                      return CustomButton(
                        title: 'Continue',
                        isLoading: state.updateIdentityInfoResult.isLoading,
                        onPressed: () {
                          if (!state.canSubmitIdentityInfo) {
                            AppHelper.showSnackBar(context,
                                message: 'Some required fields are missing');
                            return;
                          }

                          cubit.updateIdentityInfo();
                        },
                      );
                    },
                  ),
                  16.verticalSpace,
                  12.verticalSpace,
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }

  @override
  Widget wrappedRoute(BuildContext context) {
    return BlocProvider(
      create: (context) => getIt<StylistOnboardCubit>(),
      child: this,
    );
  }
}

class DocumentPicker extends StatefulWidget {
  const DocumentPicker({
    super.key,
    required this.label,
    required this.onSelected,
    this.isError = false,
    this.descriptionText,
  });

  final void Function(String) onSelected;
  final bool isError;
  final String? descriptionText;
  final String label;

  @override
  State<DocumentPicker> createState() => _DocumentPickerState();
}

class _DocumentPickerState extends State<DocumentPicker> {
  File? _file;
  Future<void> _pickFile() async {
    ImagePicker picker = ImagePicker();
    final file = await picker.pickImage(source: ImageSource.gallery);

    if (file != null) {
      _file = File(file.path);
      setState(() {});
      widget.onSelected.call(_file!.path);
    } else {}
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Row(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              widget.label,
              style: AppTextStyle.body1.copyWith(
                fontSize: 12.sp,
                color: AppColors.black,
              ),
            ),
            5.horizontalSpace,
            Text(
              '*',
              style: AppTextStyle.body1.copyWith(
                fontSize: 12.sp,
                color: AppColors.contentColorRed,
              ),
            ),
          ],
        ),
        5.verticalSpace,
        GestureDetector(
          onTap: _pickFile,
          child: DottedBorder(
            options: RoundedRectDottedBorderOptions(
              radius: Radius.circular(12),
              dashPattern: [9, 3],
              color: AppColors.primaryColor,
              strokeWidth: 2,
            ),
            child: SizedBox(
              width: double.infinity,
              height: 100,
              child: _file != null
                  ? Center(child: AppText(text: _file!.path.split('/').last))
                  : Center(
                      child: Column(
                        mainAxisSize: MainAxisSize.min,
                        children: [
                          Icon(
                            Iconsax.folder_add,
                            color: AppColors.grey2,
                          ),
                          12.verticalSpace,
                          AppText(
                            text: 'Supports: JPG, JPEG, PNG (Max 5MB each)',
                            color: AppColors.grey2,
                            fontSize: 12,
                          )
                        ],
                      ),
                    ),
            ),
          ),
        ),
        if (widget.descriptionText != null)
          Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              4.verticalSpace,
              Text(
                widget.descriptionText!,
                style: AppTextStyle.caption.copyWith(
                  letterSpacing: -0.3,
                  fontSize: 10.sp,
                  color: widget.isError ? Colors.red : AppColors.black,
                ),
              ),
            ],
          ),
      ],
    );
  }
}

class ImageTakerWidget extends StatefulWidget {
  const ImageTakerWidget({
    super.key,
    required this.label,
    required this.onSelected,
    this.isError = false,
    this.descriptionText,
  });

  final void Function(String) onSelected;
  final bool isError;
  final String? descriptionText;
  final String label;

  @override
  State<ImageTakerWidget> createState() => _ImageTakerWidgetState();
}

class _ImageTakerWidgetState extends State<ImageTakerWidget> {
  File? _file;
  Future<void> _pickFile() async {
    ImagePicker picker = ImagePicker();
    XFile? result = await picker.pickImage(source: ImageSource.camera);

    if (result != null) {
      _file = File(result.path);
      setState(() {});
      widget.onSelected.call(_file!.path);
    } else {}
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Row(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              widget.label,
              style: AppTextStyle.body1.copyWith(
                fontSize: 12.sp,
                color: AppColors.black,
              ),
            ),
            5.horizontalSpace,
            Text(
              '*',
              style: AppTextStyle.body1.copyWith(
                fontSize: 12.sp,
                color: AppColors.contentColorRed,
              ),
            ),
          ],
        ),
        5.verticalSpace,
        GestureDetector(
          onTap: _pickFile,
          child: DottedBorder(
            options: RoundedRectDottedBorderOptions(
              radius: Radius.circular(12),
              dashPattern: [9, 3],
              color: AppColors.primaryColor,
              strokeWidth: 2,
            ),
            child: SizedBox(
              width: double.infinity,
              height: 100,
              child: _file != null
                  ? Center(
                      child: Column(
                      mainAxisSize: MainAxisSize.min,
                      children: [
                        Image.file(
                          _file!,
                          height: 50,
                        ),
                        8.verticalSpace,
                        Flexible(
                            child: AppText(
                          text: _file!.path.split('/').last,
                          textAlign: TextAlign.center,
                        )),
                      ],
                    ))
                  : Center(
                      child: Column(
                        mainAxisSize: MainAxisSize.min,
                        children: [
                          Icon(
                            Iconsax.folder_add,
                            color: AppColors.grey2,
                          ),
                          12.verticalSpace,
                          AppText(
                            text: 'Supports: JPG, JPEG, PNG (Max 5MB each)',
                            color: AppColors.grey2,
                            fontSize: 12,
                          )
                        ],
                      ),
                    ),
            ),
          ),
        ),
        if (widget.descriptionText != null)
          Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              4.verticalSpace,
              Text(
                widget.descriptionText!,
                style: AppTextStyle.caption.copyWith(
                  letterSpacing: -0.3,
                  fontSize: 10.sp,
                  color: widget.isError ? Colors.red : AppColors.black,
                ),
              ),
            ],
          ),
      ],
    );
  }
}
