// Generated by Dart Safe Data Class Generator. * Change this header on extension settings *
// ignore_for_file: type=lint
import 'package:auto_route/auto_route.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:flutter_svg/svg.dart';

import 'package:snip_fair/core/di/injector.dart';
import 'package:snip_fair/core/presentation/theme/app_colors.dart';
import 'package:snip_fair/core/presentation/theme/app_textstyle.dart';
import 'package:snip_fair/core/presentation/widgets/app_text.dart';
import 'package:snip_fair/core/presentation/widgets/buttons/custom_button.dart';
import 'package:snip_fair/core/presentation/widgets/custom_appbar.dart';
import 'package:snip_fair/core/presentation/widgets/custom_text_field.dart';
import 'package:snip_fair/core/routing/routes.gr.dart';
import 'package:snip_fair/core/utils/app_helper.dart';
import 'package:snip_fair/core/utils/base/base_stateless_page.dart';
import 'package:snip_fair/core/utils/input/string_input.dart';
import 'package:snip_fair/features/stylists/onboard/cubit/stylist_onboard_cubit.dart';
import 'package:snip_fair/gen/assets.gen.dart';

@RoutePage()
class SellerBusinessCreateScreen extends BaseStatelessPage<StylistOnboardCubit>
    implements AutoRouteWrapper {
  const SellerBusinessCreateScreen({
    Key? key,
    this.fromSignUp = false,
  }) : super(key: key);

  final bool fromSignUp;

  @override
  Widget buildPage(BuildContext context) {
    final cubit = context.read<StylistOnboardCubit>();
    return BlocListener<StylistOnboardCubit, StylistOnboardState>(
      listenWhen: (previous, current) =>
          previous.updateBusinessInfoResult != current.updateBusinessInfoResult,
      listener: (context, state) {
        if (state.updateBusinessInfoResult.hasSuccess) {
          context.router
              .push(StylistBusinessIdVerifyRoute(fromSignUp: fromSignUp));
        }
      },
      child: Scaffold(
        appBar: CustomAppBar(),
        body: SafeArea(
          child: SingleChildScrollView(
            child: Padding(
              padding: const EdgeInsets.all(24),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  40.verticalSpace,
                  SvgPicture.asset(Assets.images.logo),
                  12.verticalSpace,
                  const AppText(
                    text: 'Become a Stylist',
                    color: Colors.black,
                    fontSize: 24,
                    fontWeight: FontWeight.bold,
                  ),
                  5.verticalSpace,
                  const AppText(
                    text: 'Complete your professional stylist account setup',
                  ),
                  20.verticalSpace,
                  BlocSelector<StylistOnboardCubit, StylistOnboardState,
                      StringInput>(
                    selector: (state) {
                      return state.businessName;
                    },
                    builder: (context, businessName) {
                      return CustomTextField(
                        label: 'Business/Salon name',
                        hint: 'Enter your business name',
                        isRequired: true,
                        onChanged: cubit.onBusinessNameChanged,
                        isError: businessName.isNotValid,
                        descriptionText: businessName.displayError?.message,
                      );
                    },
                  ),
                  16.verticalSpace,
                  BlocSelector<StylistOnboardCubit, StylistOnboardState,
                      StringInput>(
                    selector: (state) {
                      return state.address;
                    },
                    builder: (context, address) {
                      return CustomPlaceSearchField(
                        onSelected: (p0) {
                          if (p0 != null) {
                            cubit.onAddressChanged(p0.address);
                          }
                        },
                        label: 'Location',
                        hintText: 'Search for address',
                        isError: address.isNotValid,
                        descriptionText: address.displayError?.message,
                      );
                    },
                  ),
                  16.verticalSpace,
                  BlocSelector<StylistOnboardCubit, StylistOnboardState,
                      StringInput>(
                    selector: (state) {
                      return state.yearsOfExperience;
                    },
                    builder: (context, yearsOfExperience) {
                      return Column(
                        mainAxisSize: MainAxisSize.min,
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Row(
                            mainAxisSize: MainAxisSize.min,
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              Text(
                                'Years of experience',
                                style: AppTextStyle.body1.copyWith(
                                  fontSize: 12.sp,
                                  color: AppColors.black,
                                ),
                              ),
                              5.horizontalSpace,
                              Text(
                                '*',
                                style: AppTextStyle.body1.copyWith(
                                  fontSize: 12.sp,
                                  color: AppColors.contentColorRed,
                                ),
                              ),
                            ],
                          ),
                          5.verticalSpace,
                          DropdownButtonFormField<int>(
                            items: List.generate(20, (index) {
                              return DropdownMenuItem<int>(
                                child: AppText(
                                  text: '${index + 1}',
                                  fontSize: 16,
                                ),
                                value: index + 1,
                              );
                            }),
                            onChanged: (value) {
                              if (value != null) {
                                cubit.onYearsOfExperienceChanged(
                                    value.toString());
                              }
                            },
                            style: AppTextStyle.body1.copyWith(
                              color: AppColors.grey900,
                              fontWeight: FontWeight.w400,
                            ),
                            decoration: AppColors.inputDecoration
                                .copyWith(hintText: 'Select'),
                          ),
                          if (yearsOfExperience.displayError?.message != null)
                            Column(
                              mainAxisSize: MainAxisSize.min,
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                4.verticalSpace,
                                Text(
                                  yearsOfExperience.displayError!.message,
                                  style: AppTextStyle.caption.copyWith(
                                    letterSpacing: -0.3,
                                    fontSize: 10.sp,
                                    color: yearsOfExperience.isNotValid
                                        ? Colors.red
                                        : AppColors.black,
                                  ),
                                ),
                              ],
                            ),
                        ],
                      );
                    },
                  ),
                  16.verticalSpace,
                  BlocSelector<StylistOnboardCubit, StylistOnboardState,
                      StringInput>(
                    selector: (state) {
                      return state.bio;
                    },
                    builder: (context, bio) {
                      return CustomTextField(
                        label: 'Professional Bio',
                        hint: 'Enter your bio',
                        isRequired: true,
                        maxLines: 4,
                        onChanged: cubit.onBioChanged,
                        isError: bio.isNotValid,
                        descriptionText: bio.displayError?.message,
                      );
                    },
                  ),
                  16.verticalSpace,
                  BlocBuilder<StylistOnboardCubit, StylistOnboardState>(
                    builder: (context, state) {
                      return CustomButton(
                        title: 'Continue',
                        isLoading: state.updateBusinessInfoResult.isLoading,
                        onPressed: () {
                          if (!state.canSubmitBusinessInfo) {
                            AppHelper.showSnackBar(context,
                                message: 'Some required fields are missing');
                            return;
                          }

                          cubit.updateBusinessInfo();
                        },
                      );
                    },
                  ),
                  12.verticalSpace,
                  12.verticalSpace,
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }

  @override
  Widget wrappedRoute(BuildContext context) {
    return BlocProvider(
      create: (context) => getIt<StylistOnboardCubit>(),
      child: this,
    );
  }
}
