// Generated by Dart Safe Data Class Generator. * Change this header on extension settings *
// ignore_for_file: type=lint
import 'package:cached_network_image/cached_network_image.dart';
import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';

import 'package:snip_fair/core/presentation/theme/app_colors.dart';
import 'package:snip_fair/core/presentation/widgets/app_text.dart';
import 'package:snip_fair/core/presentation/widgets/buttons/custom_button.dart';

class PopularStyleCard extends StatelessWidget {
  const PopularStyleCard({
    super.key,
  });

  @override
  Widget build(BuildContext context) {
    return Container(
      width: 300,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(12),
      ),
      clipBehavior: Clip.antiAlias,
      child: Column(
        children: [
          Stack(
            children: [
              SizedBox(
                height: 150,
                width: double.infinity,
                child: ClipRRect(
                  borderRadius: BorderRadius.circular(12),
                  child: CachedNetworkImage(
                    imageUrl:
                        'https://snipfair.com/storage/works/media/sMFZVSnLU7yrq3qwMjV1oQJeiIbPigJX4QAlgwyy.png',
                    fit: BoxFit.cover,
                  ),
                ),
              ),
              Positioned(
                right: 12,
                top: 12,
                child: Container(
                  decoration: BoxDecoration(
                    color: const Color(0xffF9F6F5),
                    borderRadius: BorderRadius.circular(24),
                  ),
                  padding: const EdgeInsets.symmetric(
                    horizontal: 12,
                    vertical: 5,
                  ),
                  child: const AppText(
                    text: 'Nail Care',
                    fontSize: 12,
                  ),
                ),
              ),
            ],
          ),
          8.verticalSpace,
          Container(
            child: Row(
              crossAxisAlignment: CrossAxisAlignment.end,
              children: [
                8.horizontalSpace,
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.stretch,
                    children: [
                      const AppText(
                        text: 'Shaving',
                        fontWeight: FontWeight.w500,
                        fontSize: 16,
                      ),
                      const AppText(
                        text: 'Clean shave',
                        fontSize: 12,
                        color: AppColors.blackShade1,
                      ),
                    ],
                  ),
                ),
                SizedBox(
                  height: 30,
                  width: 120,
                  child: CustomButton(
                    title: 'Book Now',
                    onPressed: () {},
                    gradient: null,
                    background: Colors.black12,
                    textColor: AppColors.primaryColor,
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}
