// Generated by Dart Safe Data Class Generator. * Change this header on extension settings *
// ignore_for_file: type=lint
import 'package:auto_route/auto_route.dart';
import 'package:cached_network_image/cached_network_image.dart';
import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:snip_fair/core/domain/entities/seller_portfolio_list/seller_portfolio.dart';

import 'package:snip_fair/core/presentation/theme/app_colors.dart';
import 'package:snip_fair/core/presentation/widgets/app_text.dart';
import 'package:snip_fair/core/presentation/widgets/buttons/custom_button.dart';
import 'package:snip_fair/core/routing/routes.gr.dart';
import 'package:snip_fair/core/utils/utils.dart';
import 'package:snip_fair/gen/assets.gen.dart';

class PopularStyleCard extends StatelessWidget {
  const PopularStyleCard({
    super.key,
    required this.portfolio,
  });

  final SellerPortfolio portfolio;

  @override
  Widget build(BuildContext context) {
    return Container(
      width: 300,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(12),
      ),
      clipBehavior: Clip.antiAlias,
      child: Column(
        children: [
          Stack(
            children: [
              SizedBox(
                height: 150,
                width: double.infinity,
                child: ColoredBox(
                  color: AppColors.primaryColor.withValues(alpha: 0.3),
                  child: ClipRRect(
                    borderRadius:
                        BorderRadius.vertical(top: Radius.circular(12)),
                    child: CachedNetworkImage(
                      imageUrl:
                          portfolio.mediaUrls?.first.completeImagePath() ?? '',
                      fit: BoxFit.cover,
                      placeholder: (context, url) =>
                          Assets.images.loading.image(
                        fit: BoxFit.cover,
                      ),
                      errorWidget: (context, url, error) =>
                          const SizedBox.expand(),
                    ),
                  ),
                ),
              ),
              Positioned(
                right: 12,
                top: 12,
                child: Container(
                  decoration: BoxDecoration(
                    color: const Color(0xffF9F6F5),
                    borderRadius: BorderRadius.circular(24),
                  ),
                  padding: const EdgeInsets.symmetric(
                    horizontal: 12,
                    vertical: 5,
                  ),
                  child: AppText(
                    text: portfolio.title ?? 'N/A',
                    fontSize: 12,
                  ),
                ),
              ),
            ],
          ),
          8.verticalSpace,
          Container(
            child: Row(
              crossAxisAlignment: CrossAxisAlignment.end,
              children: [
                8.horizontalSpace,
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      AppText(
                        text: portfolio.category?.name ?? 'N/A',
                        fontWeight: FontWeight.w500,
                      ),
                    ],
                  ),
                ),
                SizedBox(
                  height: 30,
                  width: 120,
                  child: CustomButton(
                    title: 'Book Now',
                    onPressed: () {
                      context.pushRoute(
                          UpdateCreateAppointmentRoute(portfolio: portfolio));
                    },
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}
